SELECT name
FROM distrib
WHERE (id_distrib = 42
AND `name` LIKE '%y%y%'
OR  `name` LIKE '%Y%Y%')
OR  (`name` = 62
AND `name` LIKE '%y%y%'
OR  `name` LIKE '%Y%Y%')
OR (`name` = 63
AND `name` LIKE '%y%y%'
OR  `name` LIKE '%Y%Y%')
OR  (`name` = 64
AND `name` LIKE '%y%y%'
OR  `name` LIKE '%Y%Y%')
OR  (`name` = 65
AND `name` LIKE '%y%y%'
OR  `name` LIKE '%Y%Y%')
OR (`name` = 66
AND `name` LIKE '%y%y%'
OR  `name` LIKE '%Y%Y%')
OR  (`name` = 67
AND `name` LIKE '%y%y%'
OR  `name` LIKE '%Y%Y%')
OR  (`name` = 68
AND `name` LIKE '%y%y%'
OR  `name` LIKE '%Y%Y%')
OR (`name` = 69
AND `name` LIKE '%y%y%'
OR  `name` LIKE '%Y%Y%')
OR  (`name` = 71
AND `name` LIKE '%y%y%'
OR  `name` LIKE '%Y%Y%')
OR  (`name` = 88
AND `name` LIKE '%y%y%'
OR  `name` LIKE '%Y%Y%')
OR (`name` = 89
AND `name` LIKE '%y%y%'
OR  `name` LIKE '%Y%Y%')
OR  (`name` = 90
AND `name` LIKE '%y%y%'
OR  `name` LIKE '%Y%Y%')
LIMIT 2, 5;
